<!-- Slider -->
<div class="slider-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1 slider">
        <div class="flexslider">
          <ul class="slides">
            <?foreach ($this->slider as $value) {?>
              <li data-thumb="<?= $value['img_thumb']?>">
                <img src="<?= $value['img']?>">
                <div class="flex-caption">
                  <?= $value['caption']?>
                </div>
              </li>
            <?}?>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Presentation -->
<div class="presentation-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 wow fadeInLeftBig">
          <h1>We are <span class="violet">Andia</span>, a super cool design agency.</h1>
          <p>We design beautiful websites, logos and prints. Your project is safe with us.</p>
        </div>
      </div>
  </div>
</div>

<!-- Services -->
<div class="services-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="service wow fadeInUp">
          <div class="service-icon"><i class="fa fa-eye"></i></div>
          <h3>Beautiful Websites</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et...</p>
          <a class="big-link-1" href="/services">Read more</a>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="service wow fadeInDown">
          <div class="service-icon"><i class="fa fa-table"></i></div>
          <h3>Responsive Layout</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et...</p>
          <a class="big-link-1" href="/services">Read more</a>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="service wow fadeInUp">
          <div class="service-icon"><i class="fa fa-magic"></i></div>
          <h3>Awesome Logos</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et...</p>
          <a class="big-link-1" href="/services">Read more</a>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="service wow fadeInDown">
          <div class="service-icon"><i class="fa fa-print"></i></div>
          <h3>High Res Prints</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et...</p>
          <a class="big-link-1" href="/services">Read more</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Latest work -->
<div class="work-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 work-title wow fadeIn">
        <h2>Our Latest Work</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <div class="work wow fadeInUp">
          <img src="/public/img/portfolio/work1.jpg" alt="Lorem Website" data-at2x="/public/img/portfolio/work1.jpg">
          <h3>Lorem Website</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="work-bottom">
            <a class="big-link-2 view-work" href="/public/img/portfolio/work1.jpg"><i class="fa fa-search"></i></a>
            <a class="big-link-2" href="/portfolio"><i class="fa fa-link"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="work wow fadeInDown">
          <img src="/public/img/portfolio/work2.jpg" alt="Ipsum Logo" data-at2x="/public/img/portfolio/work2.jpg">
          <h3>Ipsum Logo</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="work-bottom">
            <a class="big-link-2 view-work" href="/public/img/portfolio/work2.jpg"><i class="fa fa-search"></i></a>
            <a class="big-link-2" href="/portfolio"><i class="fa fa-link"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="work wow fadeInUp">
          <img src="/public/img/portfolio/work3.jpg" alt="Dolor Prints" data-at2x="/public/img/portfolio/work3.jpg">
          <h3>Dolor Prints</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="work-bottom">
            <a class="big-link-2 view-work" href="/public/img/portfolio/work3.jpg"><i class="fa fa-search"></i></a>
            <a class="big-link-2" href="/portfolio"><i class="fa fa-link"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="work wow fadeInDown">
          <img src="/public/img/portfolio/work4.jpg" alt="Sit Amet Website" data-at2x="/public/img/portfolio/work4.jpg">
          <h3>Sit Amet Website</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="work-bottom">
            <a class="big-link-2 view-work" href="/public/img/portfolio/work4.jpg"><i class="fa fa-search"></i></a>
            <a class="big-link-2" href="/portfolio"><i class="fa fa-link"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Testimonials -->
<div class="testimonials-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 testimonials-title wow fadeIn">
        <h2>Testimonials</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1 testimonial-list">
        <div role="tabpanel">
          <!-- Tab panes -->
          <div class="tab-content">            
            <?foreach ($this->testimonials as $key => $value) {?>
              <?$i = ++$key?>
              <div role="tabpanel" class="tab-pane fade<?= $i == 1 ? ' in active' : ''?>" id="tab<?= $i?>">
                <div class="testimonial-image">
                  <img src="<?= $value['image']?>" alt="" data-at2x="<?= $value['image']?>">
                </div>
                <div class="testimonial-text">
                  <p>
                    "<?= $value['review']?>..."<br>
                    <a href="#"><?= $value['name']?>, <?= $value['job']?></a>
                  </p>
                </div>
              </div>
            <?}?>
          </div>
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <?foreach ($this->testimonials as $key => $value) {?>
              <?$i = ++$key?>
              <li role="presentation"<?= $i == 1 ? ' class="active"' : ''?>>
                <a href="#tab<?= $i?>" aria-controls="tab<?= $i?>" role="tab" data-toggle="tab"></a>
              </li>
            <?}?>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>