<!-- Page Title -->
<div class="page-title-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 wow fadeIn">
        <i class="fa fa-user"></i>
        <h1>About Us /</h1>
        <p>Below you can find more information about our company</p>
      </div>
    </div>
  </div>
</div>

<!-- About Us Text -->
<div class="about-us-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 about-us-text wow fadeInLeft">
        <h3>About Andia</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Ut wisi enim ad
          minim veniam, quis nostrud exerci tation ullamcorper <span class="violet">suscipit lobortis</span>
          nisl ut aliquip ex ea commodo consequat. Lorem ipsum <strong>dolor sit amet</strong>, consectetur adipisicing elit,
          sed do eiusmod tempor incididunt ut labore et. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
          suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing
          elit, sed do <strong>eiusmod tempor</strong> incididunt.
        </p>
        <h3>Our Mission</h3>
        <p>
          Lorem ipsum dolor sit amet, <span class="violet">consectetur adipisicing</span> elit, sed do eiusmod tempor incididunt
          ut labore et. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip
          ex ea commodo consequat. Lorem ipsum dolor sit amet, <strong>consectetur adipisicing</strong> elit, sed do eiusmod
          <span class="violet">tempor incididunt</span> ut labore et. Ut wisi enim ad minim veniam, quis nostrud exerci tation
          ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur
          adipisicing elit, sed do eiusmod tempor incididunt.
        </p>
        <h3>Why Choose Us</h3>
        <p>
          Lorem ipsum dolor sit amet, <strong>consectetur adipisicing elit</strong>, sed do eiusmod tempor incididunt ut
          labore et. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip
          ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
          ut labore et. Ut wisi enim ad minim veniam, quis <span class="violet">nostrud exerci</span> tation ullamcorper
          suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipisicing
          elit, sed do eiusmod tempor incididunt.
        </p>
      </div>
    </div>
  </div>
</div>

<!-- Meet Our Team -->
<div class="team-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 team-title wow fadeIn">
        <h2>Meet Our Team</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-3">
        <div class="team-box wow fadeInUp">
          <img src="/public/img/team/1.jpg" alt="" data-at2x="/public/img/team/1.jpg">
          <h3>John Doe</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="team-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-envelope"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-box wow fadeInDown">
          <img src="/public/img/team/2.jpg" alt="" data-at2x="/public/img/team/2.jpg">
          <h3>Jane Doe</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="team-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-envelope"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-box wow fadeInUp">
          <img src="/public/img/team/3.jpg" alt="" data-at2x="/public/img/team/3.jpg">
          <h3>Tim Brown</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="team-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-envelope"></i></a>
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="team-box wow fadeInDown">
          <img src="/public/img/team/4.jpg" alt="" data-at2x="/public/img/team/4.jpg">
          <h3>Sarah Red</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor...</p>
          <div class="team-social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-envelope"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Testimonials -->
<div class="testimonials-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 testimonials-title wow fadeIn">
        <h2>Testimonials</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1 testimonial-list">
        <div role="tabpanel">
          <!-- Tab panes -->
          <div class="tab-content">
            <?foreach ($this->testimonials as $key => $value) {?>
              <?$i = ++$key?>
              <div role="tabpanel" class="tab-pane fade<?= $i == 1 ? ' in active' : ''?>" id="tab<?= $i?>">
                <div class="testimonial-image">
                  <img src="<?= $value['image']?>" alt="" data-at2x="<?= $value['image']?>">
                </div>
                <div class="testimonial-text">
                  <p>
                    "<?= $value['review']?>..."<br>
                    <a href="#"><?= $value['name']?>, <?= $value['job']?></a>
                  </p>
                </div>
              </div>
            <?}?>
          </div>
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <?foreach ($this->testimonials as $key => $value) {?>
              <?$i = ++$key?>
              <li role="presentation"<?= $i == 1 ? ' class="active"' : ''?>>
                <a href="#tab<?= $i?>" aria-controls="tab<?= $i?>" role="tab" data-toggle="tab"></a>
              </li>
            <?}?>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>