
<!-- Page Title -->
<div class="page-title-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 wow fadeIn">
        <i class="fa fa-camera"></i>
        <h1>Portfolio /</h1>
        <p>Here is the work we've done so far</p>
      </div>
    </div>
  </div>
</div>

<!-- Portfolio -->
<div class="portfolio-container">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 portfolio-filters wow fadeInLeft">
        <a href="#" class="filter-all active">All</a> / 
        <a href="#" class="filter-web-design">Web Design</a> / 
        <a href="#" class="filter-logo-design">Logo Design</a> / 
        <a href="#" class="filter-print-design">Print Design</a>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 portfolio-masonry">
        <div class="portfolio-box web-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work1.jpg" alt="" data-at2x="/public/img/portfolio/work1.jpg">
            <div class="portfolio-box-text">
              <h3>Lorem Website</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box logo-design">
          <div class="portfolio-box-container portfolio-video" data-portfolio-big="http://vimeo.com/84910153?autoplay=0">
            <img src="/public/img/portfolio/work2.jpg" alt="" data-at2x="/public/img/portfolio/work2.jpg">
            <i class="portfolio-box-icon fa fa-play"></i>
            <div class="portfolio-box-text">
              <h3>Ipsum Logo</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box print-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work3.jpg" alt="" data-at2x="/public/img/portfolio/work3.jpg">
            <div class="portfolio-box-text">
              <h3>Dolor Prints</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box web-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work4.jpg" alt="" data-at2x="/public/img/portfolio/work4.jpg">
            <div class="portfolio-box-text">
              <h3>Sit Amet Website</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box logo-design">
          <div class="portfolio-box-container portfolio-video" data-portfolio-big="https://www.youtube.com/watch?v=tFTLxkMmY4M">
            <img src="/public/img/portfolio/work5.jpg" alt="" data-at2x="/public/img/portfolio/work5.jpg">
            <i class="portfolio-box-icon fa fa-play"></i>
            <div class="portfolio-box-text">
              <h3>Consectetur Logo</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box print-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work6.jpg" alt="" data-at2x="/public/img/portfolio/work6.jpg">
            <div class="portfolio-box-text">
              <h3>Adipisicing Print</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box web-design">
          <div class="portfolio-box-container portfolio-video" data-portfolio-big="http://vimeo.com/84910153?autoplay=0">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" 
                src="//player.vimeo.com/video/84910153?title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;color=9d426b" 
                  webkitallowfullscreen mozallowfullscreen allowfullscreen>
              </iframe>
              </div>
            <div class="portfolio-box-text">
              <h3>Elit Website</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box print-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work8.jpg" alt="" data-at2x="/public/img/portfolio/work8.jpg">
            <div class="portfolio-box-text">
              <h3>Sed Do Prints</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box web-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work9.jpg" alt="" data-at2x="/public/img/portfolio/work9.jpg">
            <div class="portfolio-box-text">
              <h3>Eiusmod Website</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box logo-design">
          <div class="portfolio-box-container portfolio-video" data-portfolio-big="https://www.youtube.com/watch?v=cfOa1a8hYP8">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" 
                src="//www.youtube.com/embed/cfOa1a8hYP8?rel=0&amp;controls=0&amp;showinfo=0" allowfullscreen>
              </iframe>
            </div>			                	
            <div class="portfolio-box-text">
              <h3>Tempor Logo</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box web-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work11.jpg" alt="" data-at2x="/public/img/portfolio/work11.jpg">
            <div class="portfolio-box-text">
              <h3>Incididunt Website</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
        <div class="portfolio-box print-design">
          <div class="portfolio-box-container">
            <img src="/public/img/portfolio/work12.jpg" alt="" data-at2x="/public/img/portfolio/work12.jpg">
            <div class="portfolio-box-text">
              <h3>Ut Labore Print</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>